[package]
name = "iwicrawl"
version = "0.1.0"
authors = ["iwikal <e.joel.nordstrom@gmail.com>"]
edition = "2018"

[dependencies]
clap = "*"
log = "*"
stderrlog = "*"
hyper = "*"
hyper-tls = "*"
robots_txt = "*"
html5ever = "*"
toks = "*"
url = "*"
futures = "0.1"
tokio = "0.1"
failure = "0.1"
